- hosts: 192.168.0.111
  vars_prompt:
  - name: username
    prompt: What is your docker os name ?
    private: no

  - name: password
    prompt: What is your password?

  tasks:
  - name: Print a message
    debug:
        msg: Logging in as {{ username }}
